image: docker:26.0.0

cache:
  paths:
    - node_modules/
    - vendor/

default:
  tags:
    - gamehub

stages:
  - test
  - post-test
#  - deploy

unit-test-job:
  stage: test
  services:
    - docker:26.0.0-dind
  before_script:
    # Start the Docker Compose services
    - docker compose --env-file "./.env.staging" --file "./docker-compose.yaml" up -d --build
  # variables:
  #   CI_DEBUG_SERVICES: "true"
  script:
    # Launch tests
    - docker exec -t gamehub-back-server-1 php artisan test
  after_script:
    # Stop the Docker Compose services
    - docker compose --env-file "./.env.staging" --file "./docker-compose.yaml" down
  retry:
    max: 1
    when: always

send-discord-job:
  stage: post-test
  variables:
    WEBHOOK_URL: "https://discord.com/api/webhooks/1300752395474698251/SvyhjBU4wYIDlfx2M-dBv0HGh7KVSUWy9SIrjX0Z5Oxk2q8z-Ol73rtBVUVDsYRSS4Em"
  script:
    - apk add --no-cache curl
    - 'curl -H "Content-Type: application/json" -d "{\"username\": \"Gamehub git - back\", \"content\": \"Tests have failed : $CI_PAGES_URL\"}" $WEBHOOK_URL'
  when: on_failure


#deploy-job:
#  stage: deploy
#  variables:
#      GIT_STRATEGY: none
#      GIT_CHECKOUT: "false"
#  script:
#    - wget --post-data "" https://test.salto.helmo.be/api/stacks/webhooks/a7140b5a-b0ce-4a8a-b744-a06868c2eb01
#  retry:
#    max: 2
#    when: always
#  only:
#    - master
