image: docker:26.0.0

cache:
  paths:
    - node_modules/
    - vendor/

include:
  - project: 'lessons/info/salto/ci'
    ref: main
    file: 'laravel.yml'

unit-test-job:
  stage: test
  services:
    - docker:26.0.0-dind
  before_script:
    # Start the Docker Compose services
    - docker compose --env-file "./.env.staging" --file "./docker-compose.yaml" up -d --build
  # variables:
  #   CI_DEBUG_SERVICES: "true"
  script:
    # Launch tests
    - docker exec -t server-1 php artisan test
  after_script:
    # Stop the Docker Compose services
    - docker compose --env-file "./.env.staging" --file "./docker-compose.yaml" down
  retry:
    max: 1
    when: always

#deploy-job:
#  stage: deploy
#  variables:
#      GIT_STRATEGY: none
#      GIT_CHECKOUT: "false"
#  script:
#    - wget --post-data "" https://test.salto.helmo.be/api/stacks/webhooks/a7140b5a-b0ce-4a8a-b744-a06868c2eb01
#  retry:
#    max: 2
#    when: always
#  only:
#    - master
