
services:
  server:
    build:
      context: .
      dockerfile: Dockerfile
    pull_policy: build
    ports:
      - mode: ingress
        target: 80
        published: "6969"
        protocol: tcp
    restart: unless-stopped
    tty: true
    depends_on:
      db:
        condition: service_healthy
  db:
    image: mysql:5.7
    command: --default-authentication-plugin=mysql_native_password
    restart: unless-stopped
    healthcheck:
      test: ["CMD", 'mysqladmin', 'ping', '-h', 'db', '-u', '${DB_USERNAME}', '-p${DB_PASSWORD}' ]
      interval: 2s
      timeout: 20s
      retries: 10
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_USER: ${DB_USERNAME}
      MYSQL_PASSWORD: ${DB_PASSWORD}
    volumes:
      - dbdata:/var/lib/mysql

networks:
  default:
    name: robvin_default
volumes:
  dbdata:
    driver: local
