
services:
  server:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: ${BACK_SERVER_CONTAINER_NAME:-gamehub-back-server}
    pull_policy: build
    restart: unless-stopped
    tty: true
    volumes:
      - publicStorage:/storage/app/
    depends_on:
      db:
        condition: service_healthy
      meilisearch:
        condition: service_started

  db:
    image: mysql:5.7
    command: --default-authentication-plugin=mysql_native_password
    restart: unless-stopped
    healthcheck:
      test: ["CMD", 'mysqladmin', 'ping', '-h', 'db', '-u', '${DB_USERNAME}', '-p${DB_PASSWORD}' ]
      interval: 2s
      timeout: 20s
      retries: 10
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_USER: ${DB_USERNAME}
      MYSQL_PASSWORD: ${DB_PASSWORD}
    volumes:
      - dbdata:/var/lib/mysql

  meilisearch:
    image: getmeili/meilisearch:v1.11
    environment:
      MEILI_MASTER_KEY: ${MEILISEARCH_KEY}
    volumes:
      - meilidate:/meili_data

networks:
  default:
    name: ${NETWORK_NAME:-gamehub-default}
volumes:
  dbdata:
    driver: local
  meilidate:
    driver: local
  publicStorage:
    driver: local
